#+title: dotfiles
#+author: dfwdfq

The main goal of this repository is to create *reproducible* custom user space for any GNU/Linux
distribution I use. It's collection of *dotfiles*, *documentation* and *bootstrapping scripts*.
*Personal philosophy of computation* included.


* What's inside?
** ~Qtile~ : window manager
I did not roll my own window manager for X server, so I use this one.
*Window manager* is a component of *desktop environment*, and I use
this one to build my own workflow. Maybe I will replace it with my own in future.

[[file:docs/qtile-docs/index.org][documentation on qtile configuration]]
** ~The holy trinity~
Since I /prefer TUI over GUI/, I consider myself a _terminal monk_.
I spend most of my time in the *terminal*, and the programs listed below are the holy trinity:
the *terminal*, where I run my *shell* to perform most operations, and *the editor*,
which is my primary instrument.
*** ~kitty~ : terminal
[[file:docs/kitty-docs/index.org][documentation on kitty configuration]]
*** ~Emacs~ : editor
[[file:docs/emacs-docs/index.org][documentation on emacs configuration]]
*** ~Fish~  : shell
[[file:docs/fish-docs/index.org][documentation on fish configuration]]

** ~custom tools~
List of programs written and used specifically by myself.
They are required by some /dotfiles/. So they should be installed.
[[file:docs/custom.org][custom tools I use]]

** ~tools~
This section describes ~non-custom~ programs, which can not
be described as /batteries/, so they should be installed manually.
[[file:docs/non-custom.org][tools I use]]

* Bootstrapping
* Personal philosophy of computation
First, such a philosophy remains personal because there is no silver bullet and
it's impossible to find a superposition that satisfies all existing user requirements.
Second, why would someone seriously call it philosophy? To answer this question,
one must understand the Unix philosophy—particularly as documented in *Eric Raymond's The Art of Unix Programming*.

So to define my personal philosophy of computation I provide 3 documents:
** Principles
They answer multiple questions *Why?*
** Rules
They answer multiple questions *How?*
** Goals
They answer multiple questions *What?*
* Assets


