#!/usr/bin/env fish

set todol ~/docs/todos/current.org
set this /home/uncle_joe/.config/scripts

cat $todol | perl $this/complete-step.pl $argv

if test $status = 67
   cat /tmp/todol > $todol
   rm /tmp/todol
   echo "step completed succesfully!"
end