#!/usr/bin/env fish

python /home/uncle_joe/.config/scripts/DONE.py $argv

if test $status = 67
   set ch_todo (batcat ~/docs/todos/current.org --style=grid | fzf --tac)
   ./set-todo.fish $ch_todo
end