#!/usr/bin/env fish

set todol ~/docs/todos/current.org
set this /home/uncle_joe/.config/scripts

set finished (cat $todol | fzf --tac)
cat $todol | perl $this/change-status.pl $finished TODO
cat /tmp/todol > $todol
echo "task status updated!"
fish $this/set-todo.fish $finished
rm /tmp/todol