#!/usr/bin/env fish

set todol ~/docs/todos/current.org
set this /home/uncle_joe/.config/scripts

if test -f ~/.current_todo
   echo "~/.current_todo fucked!"
   return 1
end   

set finished (cat ~/.current_todo)
cat $todol | perl $this/change-status.pl $finished DONE
cat /tmp/todol > $todol
echo "task status updated!"
fish $this/set-todo.fish "NO TODO!"
rm /tmp/todol